### ISSUE TITLE
Feature request: make plugin generic Microsub

### ISSUE THREAD

**Issue by metbril** [aaronpk/aperture-wordpress#1]
In the spirit of IndieWeb, it would be great if this plugin would migrate into a generic Microsub plugin. Or that it is deprecated in favour of a new, generic one. This would enable anyone to self-host an Aperture server or any other solution that conforms to the specs.

**Comment by metbril** [comment]
I'm not sure, but looking at the code, if you make the server URL a plugin setting (through the WordPress admin panel) that defaults to the hosted Aperture, this would be a first step in the requested direction.

**Comment by aaronpk** [comment]
This is definitely not intended to be a generic Microsub plugin, as that is a lot more work and a very different project. This is specifically a plugin to register an account at the hosted Aperture service.

Thankfully, there is a separate project starting that is a Microsub server for WordPress: https://github.com/jackjamieson2/yarns-microsub-server

My goal with this plugin is to have zero additional setup steps after activating the plugin to start using Microsub apps. For that reason, I am hesitant to add a setting for the server URL, since that would require a bunch of extra steps in the UI to make it work. Either choosing the server before activating the account, or having a way to change it later, and in both cases that means there would now be a separate "activate the aperture account" after activating the plugin.

If you know what you're doing, you can install your own Aperture server, change this plugin's source code to point to that, and then activate the plugin. The plugin registers with Aperture at the point of being activated, which is why I can't have a setting in the plugin for the server URL without adding additional steps.

**Comment by metbril** [comment]
I understand your motivation. Then just leave it as is and try to make the adaptation of Microsub a success.
